name: Deploy website to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Set up Pages
        uses: actions/configure-pages@v3

      - name: Upload website folder
        uses: actions/upload-pages-artifact@v1
        with:
          path: website

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
